- name: Installer Apache2 sur les hôtes Ubuntu
  hosts: localhost
  become: true
  tasks:
    - name: Installer apache2
      apt:
        name: apache2
        state: present
        update_cache: yes

