---
- name: Installer ansible-lint sur la machine de contrôle
  hosts: localhost
  become: true
  tasks:
    - name: Installer pip3 et les dépendances
      apt:
        name:
          - python3-pip
          - python3-setuptools
        state: present
        update_cache: yes

    - name: Installer ansible-lint via pip avec override PEP 668
      pip:
        name: ansible-lint
        executable: pip3
        extra_args: --break-system-packages
