---
- name: Installer et démarrer apache
  hosts: localhost
  become: true

  tasks:
    - name: Installer apache
      apt:
        name: apache2
        state: present

    - name: Démarrer apache
      service:
        name: apache2
        state: started
